### ISSUE TITLE
Was the images extracted from the same video organized in a file folder?

### ISSUE THREAD

**Issue by xujianglan** [yoctta/multiple-attention#2]
我看代码的读取过程，是需要把一个视频内的图像提取出来并放到文件夹内是吗

**Comment by RizhaoCai** [comment]
> 我看代码的读取过程，是需要把一个视频内的图像提取出来并放到文件夹内是吗

老哥请问你确认是吗？

**Comment by yoctta** [comment]
We crop out the faces from each video and save them to a folder with same size.
