### ISSUE TITLE
Training stuck for MAT

### ISSUE THREAD

**Issue by Elijah-Yi** [yoctta/multiple-attention#21]
Hi @yoctta thanks for your contributions.
when I training MAT, The training is stuck, and it's not over. I checked a lot, but I didn't find the relevant information.
![image](https://user-images.githubusercontent.com/22116117/183032434-49625b75-c296-4cfa-971d-5ef1cac9c410.png)
![image](https://user-images.githubusercontent.com/22116117/183032474-b877c05a-e094-40da-9448-a57194c1db75.png)
![image](https://user-images.githubusercontent.com/22116117/183032508-5ac0cce3-de71-4e6b-93b1-bf4327310cca.png)
![image](https://user-images.githubusercontent.com/22116117/183032543-6cc25079-472f-4e68-b328-59d3f699365a.png)
CPU shows running, Do you know what the problem is?

**Comment by Elijah-Yi** [comment]
and I found the stuck occurs at loss backward

**Comment by yoctta** [comment]
It seems like something went wrong with NCCL. I have not met such problem

**Comment by Elijah-Yi** [comment]
> It seems like something went wrong with NCCL. I have not met such problem

thanks for your reply, 
I have already, solved the problem of stuck.
Line 303 in MAT.py,  The gradient are not calculated and updated of **loss_pack2=self.train_batch(Xaug,y,jump_aux=False)**

**Comment by yoctta** [comment]
You will notice the commented lines around Line 303 in MAT.py. They would disable Sync_BN in the second forward for avoiding bugs in some versions of pytorch.
