### ISSUE TITLE
preprocess lack some files

### ISSUE THREAD

**Issue by huangyehui** [yoctta/multiple-attention#31]
hi yoctta,
       在谷歌盘盘上下载的slave_crop.py缺少一些依赖库，能否麻烦补充下，或者发一份给我(huangyehui@gmail.com)，多谢～

![image](https://github.com/yoctta/multiple-attention/assets/4714507/08a04263-c600-47ef-a20b-c89951a1cb03)

**Comment by tomolingyi** [comment]
我也有这个问题 请问您解决了吗 我的邮箱是1035966043@qq.com
