### ISSUE TITLE
Example DFDC.json file

### ISSUE THREAD

**Issue by enquestor** [yoctta/multiple-attention#9]
Can you share examples of the json files written in `data.py`? 
Or maybe only `DFDC.json` would be fine.
Thanks in advance.

**Comment by yoctta** [comment]
the json file contains locations where I storage data,  you can create your own data file.

**Comment by Allen-Hu** [comment]
@yoctta Thanks for replying. I ended up rewriting the load functions.

I would like to confirm though that the `files` variable returned in `[name]_dataset` functions is formatted as a `[[img_folder_path, is_fake]]`. Is this correct?

**Comment by yoctta** [comment]
yes


Best regards,


    Hanqing Zhao
